### PR TITLE
GridRange.is_regular was incorrect for tiles that had intersections but were pruned

### PR DESCRIPTION
**Pull request by tbenthompson**
1. Split a cell in half into two tiles.
2. Suppose one of those tiles is entirely in the alternative hypothesis domain.
3. Prune the grid range. The alt hypothesis tile is thrown out.
4. Now call `is_regular` on the remaining tile. 
5. The `n_tiles(idx) == 1` will say that the tile is regular. This is incorrect. The tile is not regular. 

This isn't a very bad bug because it just means the upper bound is a bit loose.

### CODE REVIEW

**Comment by JamesYang007** [comment]
Nice catch! How is the performance tho? Is it massively different for you as well? If so, I think it might be worth coming up with a different logic to check this.

**Comment by tbenthompson** [comment]
> Nice catch! How is the performance tho? Is it massively different for you as well? If so, I think it might be worth coming up with a different logic to check this.

I haven't checked! Can we just make an issue and leave that for later? I'm not super worried about it at the moment. Anything beyond the simplest models seems to be dominated by the statistical inference/test costs rather than the costs internal to the framework. I don't really want to optimize this stuff right now. 

Now... that failing test from the CI run! That I gotta fix! I'm surprised by that.

**Comment by tbenthompson** [comment]
Also, super surprising to me that those two snippets would have such different runtime performance. Honestly, I'm confused by that...

**Comment by JamesYang007** [comment]
LGTM

**Pull request merged**
