### PR TITLE
Use rainbow color range in visualization

### LINKED ISSUE #87: Change Plot color gradient
- Michael can't distinguish the color gradient.

### PR DESCRIPTION
**Pull request by constinit**
Resolves #87

### CODE REVIEW

**Comment by constinit** [comment]
Screenshot:
image

**Review by tbenthompson — APPROVED** [review]
APPROVE. <3

But while I'm here, we could use the "plasma" color scale. I think there's a lot of ill will amongst viz people for rainbow color scale. Plasma has a bit more interpretable or so I've heard. I'm not an expert on this stuff. 

Also, I'm guessing this will also resolve the other request of having different layers be different colors, because with a wider colorscale, it'll be less common for the foreground and background layers to be the same exact color and blend together.

**Comment by tbenthompson** [comment]
Also, this page is useful! https://plotly.com/python/builtin-colorscales/

**Comment by JamesYang007** [comment]
This is awesome!! Thanks so much for doing this!

**Comment by constinit** [comment]
I'll just expose all the options so you guys can play with it

**Pull request merged**
